export {default as banner1} from './banner1.jpg'
export {default as banner2} from './banner2.jpg'
export {default as banner3} from './banner3.jpg'
export {default as banner4} from './banner4.jpg'

export {default as stream1} from './stream-1.jpg'
export {default as stream2} from './stream-2.jpg'
export {default as stream3} from './stream-3.jpg'
export {default as stream4} from './stream-4.jpg'
export {default as stream5} from './stream-5.jpg'
export {default as stream6} from './stream-6.jpg'

export {default as streamer1} from './streamer1.jpeg'
export {default as streamer2} from './streamer2.jpeg'
export  {default as streamer3} from './streamer3.jpeg'
export {default as streamer4} from './streamer4.jpeg'
export {default as streamer5} from './streamer5.jpeg'

export {default as game1} from './game1.jpg'
export {default as game2} from './game2.jpg'
export {default as game3} from './game3.jpg'
export {default as game4} from './game4.jpg'